shut up TypeScript about this: ``` ../lib/types.ts(411,5): error TS7053: Element implicitly has an 'any' type because expression of type 'any' can't be used to index type 'BuiltInTypes'. ../lib/types.ts(413,35): error TS2339: Property 'constructor' does not exist on type 'T'. ../lib/types.ts(414,35): error TS2339: Property 'constructor' does not exist on type 'T'. ```